### ISSUE TITLE
UI thread waits on connect method

### ISSUE THREAD

**Issue by zviag** [crossbario/autobahn-android#81] opened 2015-05-31 09:58 UTC
Hello,

We are using your project in our application and it works great except for one issue: 
When connecting to server with very slow network the application freeze on connection method for few seconds (sometime more than 10!). 
I would expect the connection functionality to be totally (and real) asynchronous so no matter how long it take to get connected it won't stuck the application.
There is nothing special in our code for connecting - very similar to your sample code.

Please advise

Thanks
Zvi Agmon
Lexifone

**Comment by Mr-Gibbs** [comment] 2015-06-01 20:54
Yes this is a big problem on highly latent networks.  You seem to be doing the createSocket on the main thread and this is what blocks

**Comment by Mr-Gibbs** [comment] 2015-06-11 19:58
After further investigation it is not the createSocket that is blocking but rather the wait/notify block you have around the THREAD calling createSocket.  zviag a fix for now would be to have a separate HandlerThread that you delegate all interactions with autobahn to.

**Comment by zviag** [comment] 2015-06-14 07:54
Thanks for your response. I did try to run autobahn in different thread but had to make some changes to autobahn code in order for that to work:
- I added to ThreadHandler and  WebSocketConnection constructors a Looper parameter. The WebSocketConnection  just pass it to  ThreadHandler.
- then creating  WebSocketConnection with Looper.getMainLooper() as the Looper parameter.
With these changes I could run  autobahn in different thread.
Is this the kind of solution you suggest?

**Comment by amitprasadom** [comment] 2015-12-30 11:05
same problem i am also facing . i am binding the data in listview on message recieve  and it is freezing the application

**Comment by oberstet** [comment] 2016-04-10 14:34
yes, this is an issue that will be addressed as part of https://github.com/crossbario/autobahn-android/issues/92

the issue is: while actual socket IO already happens off the main thread, the initial connect not. and Android got stricter on that ..

closing this one, as it'll be addressed as part of above linked issue. thanks

**Closed by oberstet** 2016-04-10 14:34 UTC
